@startuml
interface LoaderInterface {
    + hasNext(): boolean
    + next(): String
}

interface SaverInterface {
    + writeNext(data: String): boolean
    + closeSaver(): boolean
}

class Loader {
    - hasNextLine: boolean
    - reader: BufferedReader
    ~ nextLine: String

    + Loader(dataFileName: String, directoryName: String) throws IOException
    + hasNext(): boolean
    + next(): String
    + getNextLine(): boolean
}

class Saver {
    ~ writer: BufferedWriter

    + Saver(dataFileName: String, directoryName: String)
    + writeNext(data: String): boolean
    + closeSaver(): boolean
}

class JsonLoader {
    - guitarDataList: ArrayList<String>
    - loadJsonData(filename: String, directoryName: String): void

    + JsonLoader(filename: String, directoryName: String)
    + getGuitarDataList(): ArrayList<String>
}

class JsonSaver {
    - filePath: String
    - inventoryArrayBuilder: JsonArrayBuilder

    + JsonSaver(dataFileName: String, directoryName: String)
    + addGuitar(serialNumber: String, price: String, builder: String, model: String,\nguitarType: String, numStrings: String, backWood: String, topWood: String): void
    + writeToFile(): boolean
}

class JsonLoaderAdapter {
    - jsonLoader: JsonLoader
    - currIndex: int
    - guitarDataList: ArrayList<String>

    + JsonLoaderAdapter(filename: String, directoryName: String)
    + hasNext(): boolean
    + next(): String
}

class JsonSaverAdapter {
    - jsonSaver: JsonSaver
    - currentGuitarFields: String[]
    - currentFieldIndex: int
    {static} + FIELDS_PER_GUITAR: int

    + JsonSaverAdapter(dataFileName: String, directoryName: String)
    + writeNext(data: String): boolean
    + closeSaver(): boolean
}

class InventoryLoader {
    {static} + loadInventory(inventory: Inventory, loader: LoaderInterface): void
}

class InventorySaver {
    {static} + saveInventory(inventory: Inventory, saver: SaverInterface): void
}

Loader .up.|> LoaderInterface
Saver .up.|> SaverInterface
JsonLoaderAdapter .up.|> LoaderInterface
JsonSaverAdapter .up.|> SaverInterface

JsonLoaderAdapter -down-> JsonLoader
JsonSaverAdapter -down-> JsonSaver

InventoryLoader .down.> LoaderInterface
InventorySaver .down.> SaverInterface

@enduml